### ISSUE TITLE
possible binary gcode compatibility

### ISSUE THREAD

**Issue by Hl2run** [DavidPhillipOster/ThumbHost3mf#1]
Hello,

would you be so kind and can you have a look at possible compatibility update for new binary gcode format?

https://hackaday.com/2023/11/28/g-code-goes-binary-with-proposed-new-format/

Thank you.

**Comment by DavidPhillipOster** [comment]
Good point. To fix this, my Quicklook plugin needs:

* a list of all the binary gcode filename suffixes
* support for the binary gcode format itself to find the thumbnails
* support for the QOI image compression format.

**Comment by DavidPhillipOster** [comment]
I've updated the source code to add:

* support for the binary gcode format itself to find the thumbnail data within the file.

* support for the QOI image format to decompress the data into an image

and at this point, everything that used to work still works, and in addition .gcode files with QOI format thumbnails also work.

binary gcode files work as expected with open in the ThumbHost3mf wrapper app: showing the thumbnail in the ThumbHost3mf window, but Quicklook doesn't seem to want to give my plugin a chance to generate the icon.

I'm still working on this. At least the ThumbnailBinaryGCode.m does a good job of extracting the thumbnail data from binary gcode files, and QOIFImageFromData.m does a good job of turning QOI data into an `NSImage`.

**Comment by DavidPhillipOster** [comment]
I found the bug: my ThumbnailProvider.m explicitly checks filename suffixes. Once I'd added the code to recognize `.bgcode`, it worked as it should.  All folded into the 1.2 release.  Thanks for the bug report!

**Comment by Hl2run** [comment]
Amazing! Thank you!
