### ISSUE TITLE
Sign application 

### ISSUE THREAD

**Issue by falkorichter** [DavidPhillipOster/ThumbHost3mf#10]
Hi, follow up to #9: https://github.com/Homebrew/homebrew-cask/pull/182172 came back, the app needs to be signed in order to be accepted as a hombrew cask.

Is it possible you provide a signed released? Self signed, not notarized might be okay.

**Comment by DavidPhillipOster** [comment]
For the Version 1.4 release, the app in the .zip:

```
codesign -dv -vv ThumbHost3mf.app
Executable=/Volumes/6T/More/Downloads/ThumbHost3mfVersion1.4/ThumbHost3mf.app/Contents/MacOS/ThumbHost3mf
Identifier=com.turbozen.-mfQuickLook
Format=app bundle with Mach-O universal (x86_64 arm64)
CodeDirectory v=20500 size=933 flags=0x10000(runtime) hashes=18+7 location=embedded
Hash type=sha256 size=32
CandidateCDHash sha256=85aecd1cc6f38e2a30b5b3dbf2629cd1344146a5
CandidateCDHashFull sha256=85aecd1cc6f38e2a30b5b3dbf2629cd1344146a5ae96d94412dce78ad000e158
Hash choices=sha256
CMSDigest=85aecd1cc6f38e2a30b5b3dbf2629cd1344146a5ae96d94412dce78ad000e158
CMSDigestType=2
CDHash=85aecd1cc6f38e2a30b5b3dbf2629cd1344146a5
Signature size=4795
Authority=Apple Development: David Phillip Oster (FSSYVLKLJK)
Authority=Apple Worldwide Developer Relations Certification Authority
Authority=Apple Root CA
Signed Time=Feb 13, 2024 at 6:58:52 PM
Info.plist entries=25
TeamIdentifier=2X3M9VFULE
Runtime Version=14.0.0
Sealed Resources version=2 rules=13 files=4
Internal requirements count=1 size=196
```

So it is signed. I will see if I can notarize it also, in a further release.

**Comment by mikeyward** [comment]
Thumbs-up on this, a notarized version would be a big plus. 

macOS Sequoia is especially persnickety about Gatekeeper and about "Known Developer" apps. 

Thank you for such a great community contribution, I love the quicklook plugin especially!

**Comment by DavidPhillipOster** [comment]
Thanks - I'm trying to understand the homebrew requirements, and it looks like I may have to submit it to them, using my own signing and notarizing. Having not submitted anything to homebrew before, that's a lot for me to learn so it hasn't yet gotten to the top of my priority list.

**Comment by MiroIsNot1337** [comment]
I'd love to install this and finally be able to see what my .3mf files contain at a glance. If you can, please get it notarized. I can't use it until it is, until there is some sort of setting to allow unsigned apps to run.

**Comment by mikeyward** [comment]
@DavidPhillipOster ah, I wasn't even thinking about the homebrew thing. Just macOS preventing me from running the current primary release without making security policy exceptions.

As in, I downloaded the app, copied it to my applications folder, and attempted to run it, but macOS refused, saying that Apple couldn't verify that the app was free of malware. I had to go into system settings to relax the security level before the app was allowed to run.

The default security setting is to only allow apps from "App Store and Known Developers", which I think includes Developer ID notarized builds.

**Comment by DavidPhillipOster** [comment]
The released version here is already signed. Also, Apple support has: https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unknown-developer-mh40616/mac - which gives you the steps to run it the first time for each of the last half dozen versions of macOS. Once you run it once macOS notes that you've allowed it to run, and it runs normally from then on. Note that ThumbHost3mf has to be in your main Applications directory or a sub folder for the macOS QuickLook system to actually use it to supply icons to Finder. Also note that Prusaslicer provides thumbnails in 3mf files but Bambuslicer does not. And even in Prusaslicer thumbnails in .gcode files is an option you have to turn on.

**Comment by MiroIsNot1337** [comment]
Thank you for the link! I was not aware of that. I am using Bambuslicer, so I'm probably out of luck anyway :/ I'll still give it a go and see if maybe they've changed something. They're usually pretty good about updating their software.

Edit: Worked great and I can see a preview of the 3mf files. Great!

**Comment by DavidPhillipOster** [comment]
Version 1.5 is also signed and notarized. I'm closing this issue an re-opening it as issue #11

**Comment by mikeyward** [comment]
Thank you!

**Comment by MiroIsNot1337** [comment]
Wow, thank you so much for the update! That was quick!!
