### ISSUE TITLE
support for homebrew (with linked PR)

### ISSUE THREAD

**Issue by falkorichter** [DavidPhillipOster/ThumbHost3mf#9]
https://github.com/Homebrew/homebrew-cask/pull/182172 has the PR :)

Let me know if there is any changes you'd like to have added

**Comment by DavidPhillipOster** [comment]
Looks good to me.

Thank you for doing this.

Note that the app exists to host a quicklook plugin which actually extracts the thumbnails in the data files to show as the Finder icons. And macOS only detects the plugin if the app is /Applications or one of its subdirectories.

**Comment by DavidPhillipOster** [comment]
https://github.com/Homebrew/homebrew-cask/pull/201050 complete
